apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-module-deployment
  labels:
    app: gate-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gate-module
  template:
    metadata:
      labels:
        app: gate-module
    spec:
      containers:
        - name: gate-module
          image: gate:1.1.14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
#            - containerPort: 5005
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: GATE_GROUP_ID
            - name: SERVICE_PORT
              value: '8080'
#            - name: JAVA_TOOL_OPTIONS
#              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms512m -Xmx1024m"