apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-module-deployment
  labels:
    app: gate-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gate-module
  template:
    metadata:
      labels:
        app: gate-module
    spec:
      containers:
        - name: gate-module
          image: gate:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: GATE_GROUP_ID
            - name: SERVICE_PORT
              value: '8080'