version: '3.8'

services:
  address_module:
    env_file:
      - "../remote.env"
    build:
      context: ../Address_module
    container_name: address_module
    restart: on-failure
    ports:
      - "9080:9080"
    environment:
      MODULE_GROUP_ID: ADDRESS_GROUP_ID
      SERVICE_PORT: 9080
    networks:
      postgres:

  product_module:
    env_file:
      - "../remote.env"
    build:
      context: ../Product_Module
    container_name: product_module
    restart: on-failure
    ports:
      - "9081:9081"
    environment:
      MODULE_GROUP_ID: PRODUCT_GROUP_ID
      SERVICE_PORT: 9081
    networks:
      postgres:

  product_category_module:
    env_file:
      - "../remote.env"
    build:
      context: ../Product_category_module
    container_name: product_category_module
    restart: on-failure
    ports:
      - "9082:9082"
    environment:
      MODULE_GROUP_ID: PRODUCT_CATEGORY_GROUP_ID
      SERVICE_PORT: 9082
    networks:
      postgres:

  store_module:
    env_file:
      - "../remote.env"
    build:
      context: ../Shop_store_module
    container_name: store_module
    restart: on-failure
    ports:
      - "9083:9083"
    environment:
      MODULE_GROUP_ID: STORE_GROUP_ID
      SERVICE_PORT: 9083
    networks:
      postgres:

  stock_module:
    env_file:
      - "../remote.env"
    build:
      context: ../Stock_module
    container_name: stock_module
    restart: on-failure
    ports:
      - "9084:9084"
    environment:
      MODULE_GROUP_ID: STOCK_GROUP_ID
      SERVICE_PORT: 9084
    networks:
      postgres:

  order_module:
    env_file:
      - "../remote.env"
    build:
      context: ../Order_module
    container_name: order_module
    restart: on-failure
    ports:
      - "9085:9085"
    environment:
      MODULE_GROUP_ID: ORDER_GROUP_ID
      SERVICE_PORT: 9085
    networks:
      postgres:

  operation_module:
    env_file:
      - "../remote.env"
    build:
      context: ../operation
    container_name: operation_module
    restart: on-failure
    ports:
      - "9086:9086"
    environment:
      MODULE_GROUP_ID: ORDER_GROUP_ID
      SERVICE_PORT: 9086
    networks:
      postgres:
      kafka-network:

  saver_module:
    env_file:
      - "../remote.env"
    build:
      context: ../saver
    container_name: saver_module
    restart: on-failure
    environment:
      MODULE_GROUP_ID: SAVER_GROUP_ID
    networks:
      postgres:
      kafka-network:

  updater_module:
    env_file:
      - "../remote.env"
    build:
      context: ../updater
    container_name: updater_module
    restart: on-failure
    environment:
      MODULE_GROUP_ID: UPDATER_GROUP_ID
    networks:
      postgres:
      kafka-network:

  gate:
    env_file:
      - "../remote.env"
    build:
      context: ../Gate
    container_name: gate
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      MODULE_GROUP_ID: GATE_GROUP_ID
  #    deploy:
  #      mode: replicated
  #      replicas: 2
    depends_on:
      - address_module
      - product_module
      - product_category_module
      - store_module
      - stock_module
      - order_module
      - operation_module

  notification:
    env_file:
      - "../remote.env"
    build:
      context: ../Notification
    container_name: notification
    restart: on-failure
    ports:
      - "8088:8088"
    environment:
      MODULE_GROUP_ID: NOTIFICATION_GROUP_ID
  #    deploy:
  #      mode: replicated
  #      replicas: 2

networks:
  postgres:
    external: true
    name: infra_postgres
  kafka-network:
    external: true
    name: infra_kafka-network