version: '3.8'

services:
  config_server:
    env_file:
      - "../.env"
    build:
      context: ../Config-server
    container_name: config_server
    restart: always
    ports:
      - "8888:8888"
    environment:
      CONFIG_SERVER_PORT: 8888

  eureka_server:
    env_file:
      - "../.env"
    build:
      context: ../Eurica_server
    container_name: eureka_server
    restart: always
    ports:
      - "8761:8761"
    environment:
      SERVICE_PORT: 8761
    depends_on:
      - config_server

  address_module:
    env_file:
      - "../.env"
    build:
      context: ../Address_module
    container_name: address_module
    restart: on-failure
    ports:
      - "9080:9080"
    environment:
      MODULE_GROUP_ID: ADDRESS_GROUP_ID
      SERVICE_PORT: 9080
    depends_on:
      - config_server
      - eureka_server
  #    deploy:
  #      mode: replicated
  #      replicas: 2

  product_module:
    env_file:
      - "../.env"
    build:
      context: ../Product_Module
    container_name: product_module
    restart: on-failure
    ports:
      - "9081:9081"
    environment:
      MODULE_GROUP_ID: PRODUCT_GROUP_ID
      SERVICE_PORT: 9081
    depends_on:
      - config_server
      - eureka_server
  #    deploy:
  #      mode: replicated
  #      replicas: 2

  product_category_module:
    env_file:
      - "../.env"
    build:
      context: ../Product_category_module
    container_name: product_category_module
    restart: on-failure
    ports:
      - "9082:9082"
    environment:
      MODULE_GROUP_ID: PRODUCT_CATEGORY_GROUP_ID
      SERVICE_PORT: 9082
    depends_on:
      - config_server
      - eureka_server
  #    deploy:
  #      mode: replicated
  #      replicas: 2

  store_module:
    env_file:
      - "../.env"
    build:
      context: ../Shop_store_module
    container_name: store_module
    restart: on-failure
    ports:
      - "9083:9083"
    environment:
      MODULE_GROUP_ID: STORE_GROUP_ID
      SERVICE_PORT: 9083
    depends_on:
      - config_server
      - eureka_server
#    deploy:
#      mode: replicated
#      replicas: 2

  stock_module:
    env_file:
      - "../.env"
    build:
      context: ../Stock_module
    container_name: stock_module
    restart: on-failure
    ports:
      - "9084:9084"
    environment:
      MODULE_GROUP_ID: STOCK_GROUP_ID
      SERVICE_PORT: 9084
    depends_on:
      - config_server
      - eureka_server
  #    deploy:
  #      mode: replicated
  #      replicas: 2

  order_module:
    env_file:
      - "../.env"
    build:
      context: ../Order_module
    container_name: order_module
    restart: on-failure
    ports:
      - "9085:9085"
    environment:
      MODULE_GROUP_ID: ORDER_GROUP_ID
      SERVICE_PORT: 9085
    depends_on:
      - config_server
      - eureka_server
  #    deploy:
  #      mode: replicated
  #      replicas: 2

  operation_module:
    env_file:
      - "../.env"
    build:
      context: ../operation
    container_name: operation_module
    restart: on-failure
    ports:
      - "9086:9086"
    environment:
      MODULE_GROUP_ID: ORDER_GROUP_ID
      SERVICE_PORT: 9086
    depends_on:
      - config_server
      - eureka_server
  #    deploy:
  #      mode: replicated
  #      replicas: 2

  payment_module:
    env_file:
      - "../.env"
    build:
      context: ../Payment_module
    container_name: payment_module
    restart: on-failure
    ports:
      - "9087:9087"
    environment:
      MODULE_GROUP_ID: PAYMENT_GROUP_ID
      SERVICE_PORT: 9087
    depends_on:
      - config_server
      - eureka_server
  #    deploy:
  #      mode: replicated
  #      replicas: 2

  shipment_module:
    env_file:
      - "../.env"
    build:
      context: ../Shipment_module
    container_name: shipment_module
    restart: on-failure
    ports:
      - "9088:9088"
    environment:
      MODULE_GROUP_ID: SHIPMENT_GROUP_ID
      SERVICE_PORT: 9088
    depends_on:
      - config_server
      - eureka_server
  #    deploy:
  #      mode: replicated
  #      replicas: 2

  saver_module:
    env_file:
      - "../.env"
    build:
      context: ../saver
    container_name: saver_module
    restart: on-failure
    environment:
      MODULE_GROUP_ID: SAVER_GROUP_ID
    depends_on:
      - config_server
      - eureka_server
  #    deploy:
  #      mode: replicated
  #      replicas: 2

  updater_module:
    env_file:
      - "../.env"
    build:
      context: ../updater
    container_name: updater_module
    restart: on-failure
    environment:
      MODULE_GROUP_ID: UPDATER_GROUP_ID
    depends_on:
      - config_server
      - eureka_server
  #    deploy:
  #      mode: replicated
  #      replicas: 2

  gate:
    env_file:
      - "../.env"
    build:
      context: ../Gate
    container_name: gate
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      MODULE_GROUP_ID: GATE_GROUP_ID
  #    deploy:
  #      mode: replicated
  #      replicas: 2
    depends_on:
      - address_module
      - product_module
      - product_category_module
      - store_module
      - stock_module
      - order_module
      - operation_module
      - config_server
      - eureka_server

  notification:
    env_file:
      - "../.env"
    build:
      context: ../Notification
    container_name: notification
    restart: on-failure
    ports:
      - "8088:8088"
    environment:
      MODULE_GROUP_ID: NOTIFICATION_GROUP_ID
    depends_on:
      - config_server
      - eureka_server
  #    deploy:
  #      mode: replicated
  #      replicas: 2