apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-module-deployment
  labels:
    app: payment-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-module
  template:
    metadata:
      labels:
        app: payment-module
    spec:
      containers:
        - name: payment-module
          image: payment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9087
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9087
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9087
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: PAYMENT_GROUP_ID
            - name: SERVICE_PORT
              value: '9087'