apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-module-deployment
  labels:
    app: shipment-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipment-module
  template:
    metadata:
      labels:
        app: shipment-module
    spec:
      containers:
        - name: shipment-module
          image: shipment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9088
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: SHIPMENT_GROUP_ID
            - name: SERVICE_PORT
              value: '9088'