apiVersion: v1
kind: Service
metadata:
  name: shipment-module-service
spec:
  selector:
    app: shipment-module
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9088
      targetPort: 9088