apiVersion: apps/v1
kind: Deployment
metadata:
  name: operation-module-deployment
  labels:
    app: operation-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operation-module
  template:
    metadata:
      labels:
        app: operation-module
    spec:
      containers:
        - name: operation-module
          image: operation:1.1.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9086
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9086
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9086
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: OPERATION_GROUP_ID
            - name: SERVICE_PORT
              value: '9086'