apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-category-module-deployment
  labels:
    app: product-category-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-category-module
  template:
    metadata:
      labels:
        app: product-category-module
    spec:
      containers:
        - name: product-category-module
          image: category:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9082
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: PRODUCT_CATEGORY_GROUP_ID
            - name: SERVICE_PORT
              value: '9082'