apiVersion: apps/v1
kind: Deployment
metadata:
  name: saver-module-deployment
  labels:
    app: saver-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saver-module
  template:
    metadata:
      labels:
        app: saver-module
    spec:
      containers:
        - name: saver-module
          image: saver:1.1.5
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: SAVER_GROUP_ID