apiVersion: apps/v1
kind: Deployment
metadata:
  name: updater-module-deployment
  labels:
    app: updater-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: updater-module
  template:
    metadata:
      labels:
        app: updater-module
    spec:
      containers:
        - name: updater-module
          image: updater:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: UPDATER_GROUP_ID