apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-module-deployment
  labels:
    app: product-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-module
  template:
    metadata:
      labels:
        app: product-module
    spec:
      containers:
        - name: product-module
          image: product:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9081
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: PRODUCT_GROUP_ID
            - name: SERVICE_PORT
              value: '9081'