apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-module-deployment
  labels:
    app: store-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-module
  template:
    metadata:
      labels:
        app: store-module
    spec:
      containers:
        - name: store-module
          image: store:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9083
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9083
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9083
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: STORE_GROUP_ID
            - name: SERVICE_PORT
              value: '9083'