apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-module-deployment
  labels:
    app: order-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-module
  template:
    metadata:
      labels:
        app: order-module
    spec:
      containers:
        - name: order-module
          image: order:1.1.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9085
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: ORDER_GROUP_ID
            - name: SERVICE_PORT
              value: '9085'