apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-module-deployment
  labels:
    app: notification-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-module
  template:
    metadata:
      labels:
        app: notification-module
    spec:
      containers:
        - name: notification-module
          image: notification:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8088
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: NOTIFICATION_GROUP_ID
            - name: SERVICE_PORT
              value: '8088'