apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-module-deployment
  labels:
    app: stock-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-module
  template:
    metadata:
      labels:
        app: stock-module
    spec:
      containers:
        - name: stock-module
          image: stock:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9084
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret
          env:
            - name: MODULE_GROUP_ID
              value: STOCK_GROUP_ID
            - name: SERVICE_PORT
              value: '9084'